garagedoor/urls.py
""" The URLs provided by the garagedoor app """
from django.urls import path

from . import views

app_name = 'garagedoor'

urlpatterns = [
    path('', views.AllDoorCodesView.as_view(), name='index'),
    path('create/', views.CreateDateCodeView.as_view(), name='create_code'),
    path('open/', views.open_door, name='open'),
    path('close/', views.close_door, name='close'),
    path('<str:pk>/', views.UpdateUseCodeView.as_view(), name='update_code'),
    path('<str:code_pk>/activation/<int:active_pk>/delete', views.delete_date_active_code,
         name='delete_date_active_code'),
    path('<str:pk>/delete', views.delete_code, name='delete_code'),
    path('<str:pk>/submit', views.confirm_code, name='confirm_code'),
    path('<str:pk>/clear', views.clear_code, name='clear_code'),
    path('<str:pk>/history', views.DoorCodeHistoryView.as_view(), name='code_history'),
]

garagedoor2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('doorcontrol/', include('garagedoor.urls')),
    path('OAuth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('', RedirectView.as_view(pattern_name='garagedoor:index', permanent=True)),
]

users/urls.py
""" The URLs provided by the users app """
from django.contrib.auth.urls import urlpatterns as auth_urlpatterns
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'users'

urlpatterns = auth_urlpatterns + [
    path('', RedirectView.as_view(pattern_name='users:login', permanent=False)),
    path('signup/', views.CreateAccount.as_view(), name='create_account'),
    path('profile/', views.UpdateProfile.as_view(), name='update_profile'),
    path('profile/password-reset', views.PasswordReset.as_view(), name='password_reset'),
]

garagedoor/forms/datecode.py
""" Form for making and modifying a date code """

from django import forms

from ..models.doorcode import US_TIMEZONES

class CreateDateCodeForm(forms.Form):
    """ A form for creating and editing the date codes """
    name = forms.CharField(max_length=1024)
    time_zone = forms.ChoiceField(required=True, choices=zip(US_TIMEZONES, US_TIMEZONES))

garagedoor/forms/passcodes.py
""" Forms for "anonymous" users to interact with forms """
from django import forms

class CreateNewPasscodeForm(forms.Form):
    """ Form to create a new passcode for the non-owner

    Parameters
    ----------
    passcode : str
        The password the invited user wants to use
    confirm_passcode : str
        Must match passcode to pass form validation
    """
    passcode = forms.CharField(max_length=128, widget=forms.PasswordInput, required=True)
    confirm_passcode = forms.CharField(max_length=128, widget=forms.PasswordInput, required=True)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['passcode'] != cleaned_data['confirm_passcode']:
            raise forms.ValidationError('Passcodes do not match')
        return cleaned_data

class SubmitPasscodeForm(forms.Form):
    """ Form for submitting a passcode to attempt to open the door

    Parameters
    ----------
    passcode : str
        The password to try to use to open the door
    """
    passcode = forms.CharField(max_length=128, widget=forms.PasswordInput, required=True)

garagedoor/views/allcodes.py
""" A view that shows all codes associated with a particular user """
import logging

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic

from ..models import DoorCode

LOGGER = logging.getLogger(__name__)

@method_decorator(login_required, name='get')
class AllDoorCodesView(generic.ListView):
    """ Displays a view with all of the codes belonging to a specific user """
    template_name = 'garagedoor/all_codes.html'
    context_object_name = 'user_codes'

    def get_queryset(self):
        """ Return all codes owned by this user """
        return DoorCode.objects.filter(user=self.request.user)

garagedoor/views/codehistory.py
""" A view that shows all codes associated with a particular user """
import logging

import pytz
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils.decorators import method_decorator
from django.views import generic

from ..models import DoorCode, DoorCodeUsed

LOGGER = logging.getLogger(__name__)

@method_decorator(login_required, name='get')
class DoorCodeHistoryView(generic.ListView):
    """ Displays a view with all of the codes belonging to a specific user """
    template_name = 'garagedoor/code_history.html'
    context_object_name = 'usage_history'

    def get_queryset(self):
        """ Raises 404 if authenticated user is not the code owner """
        code = DoorCode.objects.get(id=self.kwargs['pk'])
        if code.user != self.request.user:
            LOGGER.warning("User tried accessing somebody else's code")
            raise Http404('Code not found')
        return DoorCodeUsed.objects.filter(code=code)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Add the code to the context data and the iterator """
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['code'] = code = DoorCode.objects.get(id=self.kwargs['pk'])
        converted_times = [active.time.astimezone(pytz.timezone(code.timezone)).replace(tzinfo=None)
                           for active in self.get_queryset()]
        context['active_iterator'] = zip(self.get_queryset(), converted_times)
        return context

garagedoor/views/createcode.py
""" A view to create a new code with a specific name """
#pylint: disable=attribute-defined-outside-init
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from ..forms import CreateDateCodeForm
from ..models import DoorCode

@method_decorator(login_required, name='dispatch')
class CreateDateCodeView(FormView):
    """ View for creating a code to open the garage door """
    template_name = 'garagedoor/create_code.html'
    form_class = CreateDateCodeForm
    success_url = reverse_lazy('garagedoor:update_code')

    def form_valid(self, form):
        """ Create the new code if the form is valid """
        self.new_code = DoorCode(name=form.data['name'], user=self.request.user)
        self.new_code.save()
        return super().form_valid(form)

    def get_success_url(self):
        """ Redirect to update the code if successful """
        return reverse_lazy('garagedoor:update_code', kwargs=dict(pk=str(self.new_code.id)))

garagedoor/views/doorcontrol.py
""" Views for controlling the door """
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect

from ..myq import MyQGarageDoor, APPID, SERVICE_URL

@login_required
def open_door(request):
    """ Opens the door """
    return _set_door(request, True)

@login_required
def close_door(request):
    """ Closes the door """
    return _set_door(request, False)

def _set_door(request, open_requested=False):
    """ Sets door open or closed """
    if request.method != 'POST':
        raise Http404("Not found")
    user = request.user
    myq = MyQGarageDoor(user.myq_username, user.myq_password, SERVICE_URL, APPID,
                        user.myq_security_token)
    myq.open_door() if open_requested else myq.close_door() # pylint: disable=expression-not-assigned
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

garagedoor/views/updatecode.py
"""
This class is responsible for allowing users to update when a code is active and non-users to
set the code password and *use* it
"""
import logging
from datetime import date

import pytz
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import FormView

from ..forms import UserUpdateDoorCodeForm, SubmitPasscodeForm, CreateNewPasscodeForm
from ..models import DoorCode, DoorCodeActiveDate, DoorCodeUsed
from ..myq import MyQGarageDoor, APPID, SERVICE_URL, DoorState, MyQError

LOGGER = logging.getLogger(__name__)

class UpdateUseCodeView(FormView):
    """ The form we use depends on several things:

    1) Whether or not this code belongs to the currently logged-in user
    2) The code is initialized with a password by a non-logged-in-user
    """

    def __init__(self, *args, **kwargs):
        self._my_code = None
        super().__init__(*args, **kwargs)

    @property
    def my_code(self):
        """ The code that this view is built around """
        if self._my_code is None:
            LOGGER.debug('Getting keyword arguments for DoorCode view: %s', self.kwargs)
            self._my_code = DoorCode.objects.get(id=self.kwargs['pk'])
        return self._my_code

    def user_owns_code(self):
        """ Returns True if the authenticated user also owns this code """
        return self.request.user.is_authenticated and self.request.user == self.my_code.user

    def get_form_class(self):
        """ Gets the form class based on authentication status """
        if self.user_owns_code():
            return UserUpdateDoorCodeForm
        if self.my_code.passcode:
            return SubmitPasscodeForm
        return CreateNewPasscodeForm

    def get_initial(self):
        """ Initial data if the user is editing the code """
        if self.user_owns_code():
            return dict(start_date=date.today(), timezone='America/New_York')
        return dict()

    def get_template_names(self):
        """ Template depends on whether or not user owns the code and if the code was set """
        if self.user_owns_code():
            return ['garagedoor/user_edit_code.html']
        if self.my_code.passcode:
            return ['garagedoor/submit_code.html']
        return ['garagedoor/anonymous_create_code.html']

    def get_context_data(self, **kwargs):
        """ Adds data available to the template """
        context = super().get_context_data()
        context['code'] = self.my_code
        if self.request.user.is_authenticated and self.request.user == self.my_code.user:
            context['code_active_times'] = DoorCodeActiveDate.objects.filter(code=self.my_code)
        else:
            context['owner'] = self.my_code.user
        context.update(kwargs)
        return context

    def form_valid(self, form):
        """
        How to handle a valid form. If user owns the code, add an active date. If not, add a
        passcode if necessary. Otherwise, nothing is necessary
        """
        if self.user_owns_code():
            data = form.data
            start = date(int(form.data['start_date_year']),
                         int(form.data['start_date_month']),
                         int(form.data['start_date_day']))
            if form.data.get('end_date_year', None) not in (None, 0, '0'):
                try:
                    end = date(int(form.data['end_date_year']),
                               int(form.data['end_date_month']),
                               int(form.data['end_date_day']))
                except ValueError:
                    LOGGER.error('Failed converting %s, %s, %s', form.data['end_date_year'],
                                 form.data['end_date_month'], form.data['end_date_day'])
                    end = None
            else:
                end = None
            new_date = DoorCodeActiveDate(
                code=self.my_code,
                start_date=start,
                repeat=form.data.get('repeat', None) or None,
                end_date=end,
                start_time=form.data.get('start_time', None) or None,
                end_time=form.data.get('end_time', None) or None,
            )
            new_date.save()
        elif not self.my_code.passcode:
            data = form.data
            self.my_code.set_passcode(data['passcode'])
            self.my_code.save()
        return super().form_valid(form)

    def get_success_url(self):
        """ Redirect to code updating or inputting """
        context = self.get_context_data()
        return reverse_lazy('garagedoor:update_code', args=[context['code'].id])

def delete_date_active_code(request, code_pk, active_pk):
    """ Deletes a particular schedule of when a specific code is active """
    if request.method != 'POST' or not request.user.is_authenticated:
        LOGGER.warning('Tried to delete an active code either unauthenticated or not a POST')
        raise Http404('Page Not Found')
    try:
        code = DoorCode.objects.get(id=code_pk)
        active = DoorCodeActiveDate.objects.get(id=active_pk)
    except (DoorCode.DoesNotExist, DoorCodeActiveDate.DoesNotExist) as err:
        LOGGER.exception('Object not found')
        raise Http404('Page Not Found') from err
    if code.user != request.user or active.code != code:
        LOGGER.error('Authenticated user does not own code or code does not own active time')
        raise Http404('Page Not Found')
    active.delete()
    return redirect(reverse_lazy('garagedoor:update_code', args=[code.id]))

def delete_code(request, pk):
    """ Deletes a particular schedule of when a specific code is active """
    if request.method != 'POST' or not request.user.is_authenticated:
        LOGGER.warning('Tried to delete an active code either unauthenticated or not a POST')
        raise Http404('Page Not Found')
    try:
        code = DoorCode.objects.get(id=pk)
    except DoorCode.DoesNotExist as err:
        LOGGER.exception('Object not found')
        raise Http404('Page Not Found') from err
    if code.user != request.user:
        LOGGER.error('Authenticated user does not own code')
        raise Http404('Page Not Found')
    code.delete()
    return redirect(reverse_lazy('garagedoor:index'))

def confirm_code(request, pk):
    """ Confirms a code that was passed in """
    if request.method != 'POST':
        LOGGER.warning('Confirm code hit with %s request', request.method)
        raise Http404('Page Not Found')
    code = DoorCode.objects.get(id=pk)
    form = SubmitPasscodeForm(request.POST)
    context = dict(return_url=reverse('garagedoor:update_code', args=[code.id]))
    now = timezone.now().astimezone(pytz.timezone(code.timezone))
    code_used = DoorCodeUsed(code=code, time=now, valid=False)
    if code.check_passcode(form.data['passcode']):
        LOGGER.info('Correct code!')
        check_response = check_dates_and_toggle_door(code)
        context['response'] = check_response
        if check_response == CodeCheckReturnValues.OPENED_DOOR:
            code_used.valid = True
            code_used.state = 'Opened'
        elif check_response == CodeCheckReturnValues.CLOSED_DOOR:
            code_used.valid = True
            code_used.state = 'Closed'
        elif check_response == CodeCheckReturnValues.NOT_ACTIVE:
            code_used.reason = 'Not Active'
        else:
            code_used.reason = 'Internal Error'
    else:
        code_used.reason = 'Bad Code'
        LOGGER.warning('Incorrect passcode used for %s', code)
        context['response'] = 'Code is incorrect'
    code_used.save()
    return render(request, 'garagedoor/submit_response.html', context=context)

def clear_code(request, pk):
    """ Clears a code if the owner wants to. Non-owner will have to re-set code """
    if request.method != 'POST':
        LOGGER.warning('Clear code hit with %s request', request.method)
        raise Http404('Page Not Found')
    code = DoorCode.objects.get(id=pk)
    if request.user.is_authenticated and request.user == code.user:
        LOGGER.info('Clearing the code')
        code.passcode = None
        code.save()
        return redirect(reverse_lazy('garagedoor:index'))
    LOGGER.warning('User not authenticated or does not own code')
    raise Http404('Page Not Found')

class CodeCheckReturnValues:
    """ Effectively an Enum for connection status with the corresponding message """
    UNABLE_TO_CONNECT = 'Unable to connect to garage door'
    CLOSED_DOOR = 'Closed the garage door'
    OPENED_DOOR = 'Opened the garage door'
    NOT_ACTIVE = 'Code is not active right now'

def check_dates_and_toggle_door(code):
    """
    Checks the current time to see if this code is permitted to be used at this time, then either
    opens or closes the garage door
    """
    # Get the current time *in the timezone
    now = timezone.now().astimezone(pytz.timezone(code.timezone))
    myq = MyQGarageDoor(code.user.myq_username, code.user.myq_password, SERVICE_URL, APPID,
                        code.user.myq_security_token)
    for active_time in DoorCodeActiveDate.objects.filter(code=code):
        if _active_date_matches(active_time, now):
            try:
                door_state = myq.check_door_state()
            except MyQError:
                return CodeCheckReturnValues.UNABLE_TO_CONNECT
            if myq.security_token != code.user.myq_security_token:
                # Update it in the database
                code.user.myq_security_token = myq.security_token
                code.user.save()
            myq.toggle_door()
            if door_state in {DoorState.Closed, DoorState.Closing}:
                return CodeCheckReturnValues.OPENED_DOOR
            return CodeCheckReturnValues.CLOSED_DOOR
    return CodeCheckReturnValues.NOT_ACTIVE

def _active_date_matches(active_time, now):
    """ Returns True if "now" is valid within the active time and False otherwise """

garagedoor/templates/garagedoor/all_codes.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

{% if user.is_authenticated %}

<h3 class="centered topspaced">Review your existing door codes</h1>
<table align=center>
    {% if user_codes %}
        <tr>
            <th>Door Code</th>
            <th>Edit</th>
            <th>Delete</th>
            <th>Reset Code</th>
            <th>Usage History</th>
        </tr>
        {% for code in user_codes %}
            <tr>
                <td>
                    {{code.name}}
                </td>
                <td>
                    <a href="{% url 'garagedoor:update_code' code.id %}">
                        {% load static %}
                        <img src="{% static "images/edit.png" %}" width=20 alt="Edit"
                             name="edit{{forloop.counter}}">
                    </a>
                </td>
                <td>
                    <form method="post" action="{% url 'garagedoor:delete_code' code.id %}"
                          class="nomargin centered">
                        {% csrf_token %}
                        {% load static %}
                        <input type="image" alt="Delete" src="{% static "images/delete.png" %}"
                               width=20 class="nomargin" name="delete{{forloop.counter}}"
                               onclick="return confirm('This will delete the code for {{code.name}}')">
                    </form>
                </td>
                <td>
                    {% if code.passcode %}
                        <form method="post" action="{% url 'garagedoor:clear_code' code.id %}"
                              class="nomargin centered">
                            {% csrf_token %}
                            {% load static %}
                            <input type="image" alt="Reset" src="{% static "images/reset.png" %}"
                                   width=20 class="nomargin" name="clear{{forloop.counter}}"
                                   onclick="return confirm('This will clear the code for {{code.name}} and force it to be reset')">
                        </form>
                    {% else %}
                        Code not yet initialized
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'garagedoor:code_history' code.id %}">
                        {% load static %}
                        <img src="{% static "images/history.png" %}" width=20 alt="History"
                             name="history{{forloop.counter}}">
                    </a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
    <tr>
        <th>
            You do not have any codes defined yet. Click the button below to create your first one!
        </th>
    </tr>
    {% endif %}
</table>
<p class="centered">
    <a href="{% url 'garagedoor:create_code' %}" class="button" name="createcode">
        Create New Code
    </a>
</p>

</div>

{% else %}
<p>Please log in to see this page.</p>
{% endif %}

{% endblock %}

garagedoor/templates/garagedoor/anonymous_create_code.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

<form method="post" action="{% url 'garagedoor:update_code' code.id %}" class="centered">
{% csrf_token %}
<h1 class="centered topspaced">Code for {{owner.display_name}}'s House</h1>
<h3 class="centered topspaced">Your code is not set. Set it below</h3>
<p class="centered topspaced">
  You will only be asked to do this one time. Remember this code, as you will need it to open the
  garage door. Only the hashed passcode is stored, meaning that nobody will be able to learn your
  passcode by hacking this web application.
</p><br>
  {{form.as_table}}<br>
<input type="submit" value="Set Passcode" class="centered" name="create_code"/>
<input type="hidden" name="next" value="{{ next }}" class="centered"/>
</form>

</div>

{% endblock %}

garagedoor/templates/garagedoor/code_history.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

{% if user.is_authenticated %}
{% load tz %}

<h1 class="centered topspaced">{{code.name}} usage history</h1>
<table align=center>
    <tr>
        <th>When was it used?</th>
        <th>What happened?</th>
    </tr>
    {% for usage, my_time in active_iterator %}
        <tr>
            <td>
                <!-- Hard-code America/New_York until I find a better way to do this -->
                {{my_time}}
            </td>
            <td>
                {% if usage.valid %}
                    <b class="successtext">{{usage.state}}</b>
                {% else %}
                    <b class="errortext">{{usage.reason}}</b>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>

<p class="centered">
<a href="{% url 'garagedoor:index' %}" class="button" name="back_to_all_codes">Back To All Codes</a>
</p>

</div>

{% else %}
<p>Please log in to see this page.</p>
{% endif %}

{% endblock %}

garagedoor/templates/garagedoor/create_code.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

{% if user.is_authenticated %}

<form method="post" action="{% url 'garagedoor:create_code' %}" class="centered">
{% csrf_token %}
<h1 class="centered topspaced">Create a new door code</h1>
  {{form.as_table}}<br>
<input type="submit" value="Create Code" class="centered" name="create_code"/>
<input type="hidden" name="next" value="{{ next }}" class="centered"/>
</form>

</div>

{% else %}
<p>Please log in to see this page.</p>
{% endif %}

{% endblock %}

garagedoor/templates/garagedoor/submit_code.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

<form method="post" action="{% url 'garagedoor:confirm_code' code.id %}" class="centered">
{% csrf_token %}
<h1 class="centered topspaced">Enter code for {{owner.display_name}}'s House</h1>
  {{form.as_table}}<br>
<input type="submit" value="Submit" name="submit_code" class="centered"/>
<input type="hidden" name="next" value="{{ next }}" class="centered"/>
</form>

</div>

{% endblock %}

garagedoor/templates/garagedoor/submit_response.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

<h2 class="topspaced centered">
  {{response}}
</h2>

<p class="centered">
  <a href="{{return_url}}" class="button centered">Back to code</a>
</p>

</div>

{% endblock %}

garagedoor/templates/garagedoor/user_edit_code.html
{% extends "base.html" %}
{% block content %}
<div class="semitransparent">

{% if user.is_authenticated %}

<h3 class="centered topspaced">
  This code is currently active:
</h3>
{% if code_active_times %}
  <table align=center>
    <tr>
      <th class="centered">Between Dates</th>
      <th>Repeats</th>
      <th>Time Active</th>
      <th>Time Zone</th>
    </tr>
    {% for active_time in code_active_times %}
      <tr>
        <td>
          {{active_time.date_range_string}}
        </td>
        <td class="centered">
          {{active_time.repeat_string}}
        </td>
        <td>
          {{active_time.time_range_string}}
        </td>
        <td>
          {{code.timezone}}
        </td>
        <form method="post" class="nomargin"
              action="{% url 'garagedoor:delete_date_active_code' code.id active_time.id %}">
          <td>
            {% csrf_token %}
            {% load static %}
            <input type="image" alt="Delete" src= "{% static "images/delete.png" %}" width=20
                   class="nomargin" name="delete{{forloop.counter}}"
                   onclick="return confirm('This will delete the active time')">
          </td>
        </form>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p class="centered">This code has no active times</p>
{% endif %}

<p align=left>
  To allow someone to set this code and use it to enter the garage, share the link to this page
  with them. They will be asked to set a passcode which they can then use.
</p>

<form method="post" action="{% url 'garagedoor:update_code' code.id %}" class="centered">
{% csrf_token %}
<h3 class="centered topspaced">Pick some times when this code will be active</h1>
  {{form.as_table}}<br>
<input type="submit" value="Create Active Time" class="centered" name="create_time"/><br>
<a href="{% url 'garagedoor:index' %}" class="button" name="back_to_all_codes">Back To All Codes</a>
<input type="hidden" name="next" value="{{ next }}" class="centered"/>
</form>

</div>

{% else %}
<p class="centered">Should not be here! Not logged in!</p>
{% endif %}

{% endblock %}